#!/bin/sh

# Be an adult and check to see if things are mounted before blindly mounting these
if [ -e /proc ] && ! [ -e /proc/mounts ]; then
    mount -t proc proc /proc
fi

if [ -e /sys ] && grep -q sysfs /proc/filesystems && ! [ -e /sys/class ]; then
    mount -t sysfs sysfs /sys
fi

mkdir /dev/pts /dev/shm
chmod 777 /dev/shm
mount -t devpts devpts /dev/pts
touch /dev/mdev.seq
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

#
# We might have mounted something over /dev, see if /dev/initctl is there.
#
if test ! -p /dev/initctl
then
    rm -f /dev/initctl
    mknod -m 600 /dev/initctl p
fi
